dist: trusty
language: go

# Make sure project can also be built on travis for clones of the repo
go_import_path: github.com/vjsamuel/water

env:
  global:
    # Cross-compile for amd64 only to speed up testing.
    - GOX_FLAGS="-arch amd64"
    - GO_VERSION="$(cat .go-version)"

jobs:
  include:
    # General checks
    - os: linux
      env: TARGETS="service" 
      go: $GO_VERSION
      stage: check

    - os: linux
      env: TARGETS="service"
      go: $GO_VERSION
      stage: test
    - os: linux
      env: TARGETS="notifications"
      go: $GO_VERSION
      stage: test

script:
  - go build -o $TARGET-build github.com/vjsamuel/water/$TARGETS

addons:
  apt:
    packages:
      - python-virtualenv
      - libpcap-dev

before_install:
  - python --version
  - umask 022
  - chmod -R go-w $GOPATH/src/github.com/vjsamuel/water

